# Generated by Django 4.2.6 on 2023-10-26 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
    ]
