# Generated by Django 4.2.6 on 2023-10-26 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_category_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='tag',
        ),
    ]
