# Generated by Django 4.2.6 on 2023-11-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_recomment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomment',
            old_name='body',
            new_name='message',
        ),
    ]
