# Generated by Django 4.2.6 on 2023-11-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_body_recomment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomment',
            name='message',
            field=models.TextField(max_length=150, verbose_name='대댓글'),
        ),
    ]
