# Generated by Django 4.2.6 on 2023-11-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_recomment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='recomment',
            name='message',
        ),
        migrations.AddField(
            model_name='recomment',
            name='content',
            field=models.TextField(default=1, max_length=150, verbose_name='recomment'),
            preserve_default=False,
        ),
    ]
