# Generated by Django 4.2.6 on 2023-11-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_message_comment_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment_content',
        ),
        migrations.RenameField(
            model_name='recomment',
            old_name='content',
            new_name='recomment_content',
        ),
    ]
